language: perl
perl:
  - "5.10"

install:
  command: cpanm --installdeps --verbose .

script:
  - ./regress/scripts/travis.sh

branches:
  only:
    - calcalc
    - master

env:
  matrix:
    - VERSION=1960
      PERL_MM_USE_DEFAULT=1
    - VERSION=Divino
      PERL_MM_USE_DEFAULT=1
    - VERSION=157
